var f=Object.defineProperty;var v=(a,e,t)=>e in a?f(a,e,{enumerable:!0,configurable:!0,writable:!0,value:t}):a[e]=t;var g=(a,e,t)=>(v(a,typeof e!="symbol"?e+"":e,t),t);import{S as L,a as w,i as n}from"./assets/vendor-5401a4b0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))i(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const h of r.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&i(h)}).observe(document,{childList:!0,subtree:!0});function t(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(s){if(s.ep)return;s.ep=!0;const r=t(s);fetch(s.href,r)}})();const S=document.querySelector(".gallery"),x=document.querySelector(".loader");function m(a){x.classList.add("visually-hidden");const e=a.map(i=>`<li class="gallery-item">
		   <a class="gallery-link" href=${i.largeImageURL}>
			   <img class="gallery-image" src=${i.webformatURL} alt="${i.tags}" />
		   </a>
		   <div class="container">
			   <div class="container-text"><h3 class="titel-text">Likes</h3><p class="text">${i.likes}</p></div>
			   <div class="container-text"><h3 class="titel-text">Views</h3><p class="text">${i.views}</p></div>
			   <div class="container-text"><h3 class="titel-text">Comments</h3><p class="text">${i.comments}</p></div>
			   <div class="container-text"><h3 class="titel-text">Dowloads</h3><p class="text">${i.downloads}</p></div>
		   </div>
	   </li>`).join("");S.insertAdjacentHTML("beforeend",e),new L(".gallery-link",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()}const u=class u{constructor(){this.BASE_URL="https://pixabay.com/api/",this.query=null,this.page=1,this.totalResult=0}async getInfoArticles(){const e={key:"42169950-0e8cca4ed1d3fcef898dec13a",q:this.query,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:u.PAGE_SIZE,page:this.page};return await w.get(`${this.BASE_URL}`,{params:e}).then(t=>{if(t.data.hits.length===0)throw new Error("Error");return t.data})}};g(u,"PAGE_SIZE",15);let c=u;const y=document.querySelector(".js-form"),E=document.querySelector(".gallery"),p=document.querySelector(".loader"),l=document.querySelector(".js-load-more"),o=new c;let d=0;y.addEventListener("submit",q);l.addEventListener("click",b);async function q(a){a.preventDefault();const e=y.elements.text.value.trim();if(y.elements.text.value="",E.innerHTML="",e){p.classList.remove("visually-hidden"),o.page=1,o.query=e;try{const t=await o.getInfoArticles(e);d=Math.ceil(t.totalHits/c.PAGE_SIZE),m(t.hits),o.page===d?(l.classList.add("visually-hidden"),n.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):l.classList.remove("visually-hidden")}catch{l.classList.add("visually-hidden"),p.classList.add("visually-hidden"),n.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}}else n.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}async function b(){if(p.classList.remove("visually-hidden"),l.classList.add("visually-hidden"),o.page<d){l.classList.remove("visually-hidden"),o.page+=1;const a=await o.getInfoArticles();m(a.hits);const t=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t.height*2,behavior:"smooth"})}o.page===d&&(l.classList.add("visually-hidden"),n.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}
//# sourceMappingURL=commonHelpers.js.map
